name: zaqapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  curved_navigation_bar: ^1.0.6

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.1
  firebase_analytics: ^11.1.0

  # State management
  provider: ^6.1.2

  # PDF viewer
  easy_pdf_viewer: ^1.0.0

  # Payment (Razorpay)
  razorpay_flutter: ^1.3.6

  # Env variables
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logobase.png


flutter_native_splash:
  color: "#ffffff"          # background color
  image: assets/logobase.png    # your logo (copy into assets/)
  android: true
  ios: true
  web: true
